package View;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author juan.castro17
 */
public class AD2 extends javax.swing.JFrame {

    /**
     * Creates new form X1
     */
    public AD2() {
        System.setProperty("sun.java2d.uiScale", "1.0");
        FlatDarkLaf.setup(); // Sets the FlatLaf LookAndFeel as the main theme for the JFrame.
        initComponents();
        
        this.setLocationRelativeTo(null); //Centers the window on-screen.
        this.setTitle("Trabajadores"); // Set the title for the JFrame.
        
        Image faviconX1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/View_IconAdminZOO.png"));
        this.setIconImage(faviconX1);
        
        Image logoZRV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/ZRVBW@3x.png"));
        lbZRVLogo.setIcon(new ImageIcon(logoZRV.getScaledInstance(lbZRVLogo.getWidth(), lbZRVLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));

        Image logoZoo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/zoo!WhiteLogo.png"));
        lbZooLogo.setIcon(new ImageIcon(logoZoo.getScaledInstance(lbZooLogo.getWidth(), lbZooLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgPanelRound = new Clases.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGeneratedReports = new javax.swing.JTable();
        lbTotalExpenses = new java.awt.Label();
        lbGeneratedReports = new java.awt.Label();
        lbTotalExpensesValue = new java.awt.Label();
        lbTotalIncomes = new java.awt.Label();
        lbTotalIncomesValue = new java.awt.Label();
        btDeleteReport = new javax.swing.JButton();
        lbReportType = new java.awt.Label();
        lbReportTitle = new java.awt.Label();
        lbZooLogo = new javax.swing.JLabel();
        lbZRVLogo = new javax.swing.JLabel();
        btGeneratePDF1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(35, 35, 35));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanelRound.setBackground(new java.awt.Color(51, 51, 51));
        bgPanelRound.setRoundBottomLeft(15);
        bgPanelRound.setRoundBottomRight(15);
        bgPanelRound.setRoundTopLeft(15);
        bgPanelRound.setRoundTopRight(15);
        bgPanelRound.setLayout(null);

        tbGeneratedReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Fecha", "Sueldo", "Puesto", "Surcusal"
            }
        ));
        jScrollPane1.setViewportView(tbGeneratedReports);

        bgPanelRound.add(jScrollPane1);
        jScrollPane1.setBounds(10, 35, 680, 280);

        lbTotalExpenses.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalExpenses.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTotalExpenses.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalExpenses.setText("Profesional:");
        bgPanelRound.add(lbTotalExpenses);
        lbTotalExpenses.setBounds(10, 350, 140, 32);

        lbGeneratedReports.setBackground(new java.awt.Color(51, 51, 51));
        lbGeneratedReports.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lbGeneratedReports.setForeground(new java.awt.Color(255, 255, 255));
        lbGeneratedReports.setText("Trabajadores");
        bgPanelRound.add(lbGeneratedReports);
        lbGeneratedReports.setBounds(10, 0, 296, 32);

        lbTotalExpensesValue.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalExpensesValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTotalExpensesValue.setForeground(new java.awt.Color(255, 153, 0));
        bgPanelRound.add(lbTotalExpensesValue);
        lbTotalExpensesValue.setBounds(160, 350, 140, 32);

        lbTotalIncomes.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalIncomes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTotalIncomes.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalIncomes.setText("Nombre:");
        bgPanelRound.add(lbTotalIncomes);
        lbTotalIncomes.setBounds(10, 320, 150, 32);

        lbTotalIncomesValue.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalIncomesValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTotalIncomesValue.setForeground(new java.awt.Color(255, 153, 0));
        bgPanelRound.add(lbTotalIncomesValue);
        lbTotalIncomesValue.setBounds(160, 320, 140, 32);

        btDeleteReport.setBackground(new java.awt.Color(51, 51, 51));
        btDeleteReport.setForeground(new java.awt.Color(255, 255, 255));
        btDeleteReport.setText("Eliminar Empleado");
        bgPanelRound.add(btDeleteReport);
        btDeleteReport.setBounds(560, 340, 130, 23);

        bg.add(bgPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 390));

        lbReportType.setBackground(new java.awt.Color(35, 35, 35));
        lbReportType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbReportType.setForeground(new java.awt.Color(255, 255, 255));
        lbReportType.setText("Trabajador:");
        bg.add(lbReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        lbReportTitle.setBackground(new java.awt.Color(35, 35, 35));
        lbReportTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbReportTitle.setForeground(new java.awt.Color(255, 153, 0));
        lbReportTitle.setText("Recursos Humanos");
        bg.add(lbReportTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, -1, -1));

        lbZooLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        lbZooLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbZooLogoMouseClicked(evt);
            }
        });
        bg.add(lbZooLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 90, 90));

        lbZRVLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        bg.add(lbZRVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 60));

        btGeneratePDF1.setText("Buscar");
        bg.add(btGeneratePDF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 70, 20));

        jTextField1.setText("Ingrese el ID del trabajador");
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 280, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbZooLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbZooLogoMouseClicked
        IS1 AdminMainScreen = new IS1();
        this.dispose();
        AdminMainScreen.setVisible(true);
    }//GEN-LAST:event_lbZooLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch (Exception e){
            
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AD2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private Clases.PanelRound bgPanelRound;
    private javax.swing.JButton btDeleteReport;
    private javax.swing.JButton btGeneratePDF1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label lbGeneratedReports;
    private java.awt.Label lbReportTitle;
    private java.awt.Label lbReportType;
    private java.awt.Label lbTotalExpenses;
    private java.awt.Label lbTotalExpensesValue;
    private java.awt.Label lbTotalIncomes;
    private java.awt.Label lbTotalIncomesValue;
    private javax.swing.JLabel lbZRVLogo;
    private javax.swing.JLabel lbZooLogo;
    private javax.swing.JTable tbGeneratedReports;
    // End of variables declaration//GEN-END:variables
}
