package View;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author juan.castro17
 */
public class IS1 extends javax.swing.JFrame {

    /**
     * Creates new form X1
     */
    public IS1() {
        System.setProperty("sun.java2d.uiScale", "1.0");
        FlatDarkLaf.setup(); // Sets the FlatLaf LookAndFeel as the main theme for the JFrame.
        initComponents();
        
        this.setLocationRelativeTo(null); //Centers the window on-screen.
        this.setTitle("Departamento Administrativo"); // Set the title for the JFrame.
        
        Image faviconX1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/View_IconAdminZOO.png"));
        this.setIconImage(faviconX1);
        
        Image logoZRV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/zoo!WhiteLogo.png"));
        lbZooLogo.setIcon(new ImageIcon(logoZRV.getScaledInstance(lbZooLogo.getWidth(), lbZooLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lbZooLogo = new javax.swing.JLabel();
        bgPanelRound = new Clases.PanelRound();
        btAdministrativeDept = new javax.swing.JButton();
        btCommercialDept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(320, 370));
        setMinimumSize(new java.awt.Dimension(320, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(320, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setMaximumSize(new java.awt.Dimension(320, 370));
        bg.setMinimumSize(new java.awt.Dimension(320, 370));
        bg.setPreferredSize(new java.awt.Dimension(320, 370));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbZooLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        bg.add(lbZooLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 90, 90));

        bgPanelRound.setBackground(new java.awt.Color(255, 153, 0));
        bgPanelRound.setRoundBottomLeft(15);
        bgPanelRound.setRoundBottomRight(15);
        bgPanelRound.setRoundTopLeft(15);
        bgPanelRound.setRoundTopRight(15);
        bgPanelRound.setLayout(null);

        btAdministrativeDept.setBackground(new java.awt.Color(242, 242, 242));
        btAdministrativeDept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btAdministrativeDept.setForeground(new java.awt.Color(255, 255, 255));
        btAdministrativeDept.setText("Administrativo");
        btAdministrativeDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdministrativeDeptActionPerformed(evt);
            }
        });
        bgPanelRound.add(btAdministrativeDept);
        btAdministrativeDept.setBounds(30, 240, 220, 29);

        btCommercialDept.setBackground(new java.awt.Color(242, 242, 242));
        btCommercialDept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btCommercialDept.setForeground(new java.awt.Color(255, 255, 255));
        btCommercialDept.setText("Comercial");
        btCommercialDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommercialDeptActionPerformed(evt);
            }
        });
        bgPanelRound.add(btCommercialDept);
        btCommercialDept.setBounds(30, 190, 220, 29);

        bg.add(bgPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 300));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdministrativeDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdministrativeDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdministrativeDeptActionPerformed

    private void btCommercialDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommercialDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCommercialDeptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch (Exception e){
            
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private Clases.PanelRound bgPanelRound;
    private javax.swing.JButton btAdministrativeDept;
    private javax.swing.JButton btCommercialDept;
    private javax.swing.JLabel lbZooLogo;
    // End of variables declaration//GEN-END:variables
}
