package View;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author juan.castro17
 */
public class PAAdd extends javax.swing.JFrame {

    /**
     * Creates new form X1
     */
    public PAAdd() {
        //define tamaño
        System.setProperty("sun.java2d.uiScale", "1.0");
        FlatDarkLaf.setup(); // Sets the FlatLaf LookAndFeel as the main theme for the JFrame.
        initComponents();
        //ubica el nombre de la ventana 
        this.setLocationRelativeTo(null); //Centers the window on-screen.
        this.setTitle("Departamento Administrativo"); // Set the title for the JFrame.
        //icono de la ventana 
        Image faviconX1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/View_IconAdminZOO.png"));
        this.setIconImage(faviconX1);
        //logo del recadro debajo del logo
        Image logoZRV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/zoo!Logo.png"));
        lbZooLogo.setIcon(new ImageIcon(logoZRV.getScaledInstance(lbZooLogo.getWidth(), lbZooLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        bg = new javax.swing.JPanel();
        bgPanelRound = new Clases.PanelRound();
        lbID = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        lbPlan = new javax.swing.JLabel();
        txValue = new javax.swing.JTextField();
        lbValue = new javax.swing.JLabel();
        lbDetails = new javax.swing.JLabel();
        txDetails = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txPlan = new javax.swing.JTextField();
        btLogisticPlan = new javax.swing.JButton();
        lbZooLogo = new javax.swing.JLabel();
        lbPlanTitle1 = new java.awt.Label();
        lbPlanTitle2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(320, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(320, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(35, 35, 35));
        bg.setMaximumSize(new java.awt.Dimension(320, 370));
        bg.setMinimumSize(new java.awt.Dimension(320, 370));
        bg.setPreferredSize(new java.awt.Dimension(320, 370));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanelRound.setBackground(new java.awt.Color(51, 51, 51));
        bgPanelRound.setRoundBottomLeft(15);
        bgPanelRound.setRoundBottomRight(15);
        bgPanelRound.setRoundTopLeft(15);
        bgPanelRound.setRoundTopRight(15);
        bgPanelRound.setLayout(null);

        lbID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbID.setForeground(new java.awt.Color(242, 242, 242));
        lbID.setText("ID Plan:");
        bgPanelRound.add(lbID);
        lbID.setBounds(10, 10, 70, 16);

        txID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txID.setText("Ingrese el ID del plan");
        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });
        bgPanelRound.add(txID);
        txID.setBounds(80, 10, 190, 22);

        lbPlan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbPlan.setForeground(new java.awt.Color(242, 242, 242));
        lbPlan.setText("Plan:");
        bgPanelRound.add(lbPlan);
        lbPlan.setBounds(10, 40, 70, 16);

        txValue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txValue.setText("Ingrese el valor del plan");
        txValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txValueActionPerformed(evt);
            }
        });
        bgPanelRound.add(txValue);
        txValue.setBounds(80, 70, 190, 22);

        lbValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbValue.setForeground(new java.awt.Color(242, 242, 242));
        lbValue.setText("Valor:");
        bgPanelRound.add(lbValue);
        lbValue.setBounds(10, 70, 70, 16);

        lbDetails.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbDetails.setForeground(new java.awt.Color(242, 242, 242));
        lbDetails.setText("Especificaciones:");
        bgPanelRound.add(lbDetails);
        lbDetails.setBounds(10, 100, 170, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ingresa las especificaciones del plan");
        txDetails.setViewportView(jTextArea1);

        bgPanelRound.add(txDetails);
        txDetails.setBounds(10, 120, 260, 130);

        txPlan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txPlan.setText("Ingrese el plan");
        txPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPlanActionPerformed(evt);
            }
        });
        bgPanelRound.add(txPlan);
        txPlan.setBounds(80, 40, 190, 22);

        bg.add(bgPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 260));

        btLogisticPlan.setBackground(new java.awt.Color(255, 153, 0));
        btLogisticPlan.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btLogisticPlan.setForeground(new java.awt.Color(242, 242, 242));
        btLogisticPlan.setText("+");
        btLogisticPlan.setActionCommand("Añadir");
        btLogisticPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLogisticPlan.setFocusPainted(false);
        btLogisticPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogisticPlanActionPerformed(evt);
            }
        });
        bg.add(btLogisticPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, 30));

        lbZooLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbZooLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        lbZooLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbZooLogoMouseClicked(evt);
            }
        });
        bg.add(lbZooLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2, 90, 45));

        lbPlanTitle1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbPlanTitle1.setForeground(new java.awt.Color(188, 38, 73));
        lbPlanTitle1.setText("Plan");
        bg.add(lbPlanTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lbPlanTitle2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbPlanTitle2.setForeground(new java.awt.Color(255, 153, 0));
        lbPlanTitle2.setText("Nuevo ");
        bg.add(lbPlanTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogisticPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogisticPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogisticPlanActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void txValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txValueActionPerformed

    private void txPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPlanActionPerformed

    private void lbZooLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbZooLogoMouseClicked
         AD3 ReportWindow = new AD3();
       this.dispose();
       ReportWindow.setVisible(true);
    }//GEN-LAST:event_lbZooLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch (Exception e){
            
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private Clases.PanelRound bgPanelRound;
    private javax.swing.JButton btLogisticPlan;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbDetails;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbPlan;
    private java.awt.Label lbPlanTitle1;
    private java.awt.Label lbPlanTitle2;
    private javax.swing.JLabel lbValue;
    private javax.swing.JLabel lbZooLogo;
    private javax.swing.JScrollPane txDetails;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txPlan;
    private javax.swing.JTextField txValue;
    // End of variables declaration//GEN-END:variables
}
