package View.Cormercial;

import com.zoosantafe.zoologico.CMProAdd;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author juan.castro17
 */
public class CM1 extends javax.swing.JFrame {

    /**
     * Creates new form X1
     */
    public CM1() {
        System.setProperty("sun.java2d.uiScale", "1.0");
        FlatDarkLaf.setup(); // Sets the FlatLaf LookAndFeel as the main theme for the JFrame.
        initComponents();
        
        this.setLocationRelativeTo(null); //Centers the window on-screen.
        this.setTitle("Ventas"); // Set the title for the JFrame.
        
        Image faviconX1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/View_IconCommZOO.png"));
        this.setIconImage(faviconX1);
        
        Image logoZRV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/ZRVC@3x.png"));
        lbZRVLogo.setIcon(new ImageIcon(logoZRV.getScaledInstance(lbZRVLogo.getWidth(), lbZRVLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));

        Image logoZoo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/zoo!Logo.png"));
        lbZooLogo.setIcon(new ImageIcon(logoZoo.getScaledInstance(lbZooLogo.getWidth(), lbZooLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgPanelRound = new Clases.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducts = new javax.swing.JTable();
        lbDiscount = new java.awt.Label();
        lbTotalSaleValue = new java.awt.Label();
        btNewSale = new javax.swing.JButton();
        btBill = new javax.swing.JButton();
        lbTotalSale2 = new java.awt.Label();
        txDiscount = new javax.swing.JTextField();
        lbIDGenerado = new javax.swing.JLabel();
        lbProducto = new java.awt.Label();
        lbSalesTitle = new java.awt.Label();
        lbZRVLogo = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        btAddProduct = new javax.swing.JButton();
        lbAmount = new java.awt.Label();
        spAmount = new javax.swing.JSpinner();
        lbZooLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(35, 35, 35));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanelRound.setBackground(new java.awt.Color(51, 51, 51));
        bgPanelRound.setRoundBottomLeft(15);
        bgPanelRound.setRoundBottomRight(15);
        bgPanelRound.setRoundTopLeft(15);
        bgPanelRound.setRoundTopRight(15);
        bgPanelRound.setLayout(null);

        tbProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod", "Producto", "Cantidad", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tbProducts);

        bgPanelRound.add(jScrollPane1);
        jScrollPane1.setBounds(10, 145, 680, 170);

        lbDiscount.setBackground(new java.awt.Color(51, 51, 51));
        lbDiscount.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lbDiscount.setText("Descuento");
        bgPanelRound.add(lbDiscount);
        lbDiscount.setBounds(20, 330, 110, 40);

        lbTotalSaleValue.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalSaleValue.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lbTotalSaleValue.setForeground(new java.awt.Color(188, 38, 73));
        lbTotalSaleValue.setText("$00.000,00");
        bgPanelRound.add(lbTotalSaleValue);
        lbTotalSaleValue.setBounds(410, 330, 140, 40);

        btNewSale.setBackground(new java.awt.Color(51, 51, 51));
        btNewSale.setForeground(new java.awt.Color(255, 255, 255));
        btNewSale.setText("Nueva venta");
        btNewSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSaleActionPerformed(evt);
            }
        });
        bgPanelRound.add(btNewSale);
        btNewSale.setBounds(560, 357, 130, 23);

        btBill.setBackground(new java.awt.Color(51, 51, 51));
        btBill.setForeground(new java.awt.Color(255, 255, 255));
        btBill.setText("Facturar");
        bgPanelRound.add(btBill);
        btBill.setBounds(560, 325, 130, 23);

        lbTotalSale2.setBackground(new java.awt.Color(51, 51, 51));
        lbTotalSale2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lbTotalSale2.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalSale2.setText("Valor total");
        bgPanelRound.add(lbTotalSale2);
        lbTotalSale2.setBounds(290, 330, 110, 40);

        txDiscount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txDiscount.setForeground(new java.awt.Color(188, 38, 73));
        bgPanelRound.add(txDiscount);
        txDiscount.setBounds(140, 330, 140, 40);

        lbIDGenerado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbIDGenerado.setForeground(new java.awt.Color(242, 242, 242));
        lbIDGenerado.setText("Cliente ");
        bgPanelRound.add(lbIDGenerado);
        lbIDGenerado.setBounds(20, 20, 70, 16);

        bg.add(bgPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 390));

        lbProducto.setBackground(new java.awt.Color(35, 35, 35));
        lbProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbProducto.setText("Producto");
        bg.add(lbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        lbSalesTitle.setBackground(new java.awt.Color(35, 35, 35));
        lbSalesTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbSalesTitle.setForeground(new java.awt.Color(188, 38, 73));
        lbSalesTitle.setText("Ventas");
        bg.add(lbSalesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, -1, -1));

        lbZRVLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        bg.add(lbZRVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 60));

        cbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bg.add(cbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));

        btAddProduct.setText("Agregar producto");
        btAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductActionPerformed(evt);
            }
        });
        bg.add(btAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 130, -1));

        lbAmount.setBackground(new java.awt.Color(35, 35, 35));
        lbAmount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbAmount.setForeground(new java.awt.Color(255, 255, 255));
        lbAmount.setText("Cantidad");
        bg.add(lbAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 70, 20));
        bg.add(spAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 50, -1));

        lbZooLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbZooLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        lbZooLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbZooLogoMouseClicked(evt);
            }
        });
        bg.add(lbZooLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 90, 45));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddProductActionPerformed

    private void lbZooLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbZooLogoMouseClicked
        IS2 MainScreen = new IS2();
        this.dispose();
        MainScreen.setVisible(true);
    }//GEN-LAST:event_lbZooLogoMouseClicked

    private void btNewSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSaleActionPerformed
       CMProAdd MainScreen = new CMProAdd();
        this.dispose();
        MainScreen.setVisible(true);
                                    
    }//GEN-LAST:event_btNewSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch (Exception e){
            
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CM1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private Clases.PanelRound bgPanelRound;
    private javax.swing.JButton btAddProduct;
    private javax.swing.JButton btBill;
    private javax.swing.JButton btNewSale;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lbAmount;
    private java.awt.Label lbDiscount;
    private javax.swing.JLabel lbIDGenerado;
    private java.awt.Label lbProducto;
    private java.awt.Label lbSalesTitle;
    private java.awt.Label lbTotalSale2;
    private java.awt.Label lbTotalSaleValue;
    private javax.swing.JLabel lbZRVLogo;
    private javax.swing.JLabel lbZooLogo;
    private javax.swing.JSpinner spAmount;
    private javax.swing.JTable tbProducts;
    private javax.swing.JTextField txDiscount;
    // End of variables declaration//GEN-END:variables
}
