package View.Cormercial;

import View.X1;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author juan.castro17
 */
public class IS2 extends javax.swing.JFrame {

    /**
     * Creates new form X1
     */
    public IS2() {
        //define tamaño
        System.setProperty("sun.java2d.uiScale", "1.0");
        FlatDarkLaf.setup(); // Sets the FlatLaf LookAndFeel as the main theme for the JFrame.
        initComponents();
        //ubica el nombre de la ventana 
        this.setLocationRelativeTo(null); //Centers the window on-screen.
        this.setTitle("Departamento Comercial"); // Set the title for the JFrame.
        //icono de la ventana 
        Image faviconX1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/View_IconCommZOO.png"));
        this.setIconImage(faviconX1);
        //logo del recadro debajo del logo
        Image logoZRV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/zoo!Logo.png"));
        lbZooLogo.setIcon(new ImageIcon(logoZRV.getScaledInstance(lbZooLogo.getWidth(), lbZooLogo.getHeight(), Image.SCALE_AREA_AVERAGING)));
       
        Image logoZV = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/ticket.png"));
        lbTicket.setIcon(new ImageIcon(logoZV.getScaledInstance(lbTicket.getWidth(), lbTicket.getHeight(), Image.SCALE_AREA_AVERAGING)));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgPanelRound = new Clases.PanelRound();
        btComercialShopping = new javax.swing.JButton();
        btComercialSale = new javax.swing.JButton();
        lbTicket = new javax.swing.JLabel();
        LbComercialTitle = new java.awt.Label();
        lbZooLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(320, 370));
        setResizable(false);
        setSize(new java.awt.Dimension(320, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(35, 35, 35));
        bg.setMaximumSize(new java.awt.Dimension(320, 370));
        bg.setMinimumSize(new java.awt.Dimension(320, 370));
        bg.setPreferredSize(new java.awt.Dimension(320, 370));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanelRound.setBackground(new java.awt.Color(51, 51, 51));
        bgPanelRound.setRoundBottomLeft(15);
        bgPanelRound.setRoundBottomRight(15);
        bgPanelRound.setRoundTopLeft(15);
        bgPanelRound.setRoundTopRight(15);
        bgPanelRound.setLayout(null);

        btComercialShopping.setBackground(new java.awt.Color(188, 38, 73));
        btComercialShopping.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btComercialShopping.setForeground(new java.awt.Color(242, 242, 242));
        btComercialShopping.setText("Compra");
        btComercialShopping.setFocusPainted(false);
        btComercialShopping.setMaximumSize(new java.awt.Dimension(123, 49));
        btComercialShopping.setMinimumSize(new java.awt.Dimension(123, 49));
        btComercialShopping.setOpaque(true);
        btComercialShopping.setPreferredSize(new java.awt.Dimension(123, 49));
        btComercialShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComercialShoppingActionPerformed(evt);
            }
        });
        bgPanelRound.add(btComercialShopping);
        btComercialShopping.setBounds(30, 230, 220, 40);

        btComercialSale.setBackground(new java.awt.Color(188, 38, 73));
        btComercialSale.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btComercialSale.setForeground(new java.awt.Color(242, 242, 242));
        btComercialSale.setText("Venta");
        btComercialSale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btComercialSale.setFocusPainted(false);
        btComercialSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComercialSaleActionPerformed(evt);
            }
        });
        bgPanelRound.add(btComercialSale);
        btComercialSale.setBounds(30, 170, 220, 40);

        lbTicket.setMaximumSize(new java.awt.Dimension(549, 267));
        bgPanelRound.add(lbTicket);
        lbTicket.setBounds(70, 10, 150, 150);

        bg.add(bgPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 300));

        LbComercialTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LbComercialTitle.setForeground(new java.awt.Color(188, 38, 73));
        LbComercialTitle.setText("Comercial");
        bg.add(LbComercialTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        lbZooLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbZooLogo.setMaximumSize(new java.awt.Dimension(549, 267));
        lbZooLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbZooLogoMouseClicked(evt);
            }
        });
        bg.add(lbZooLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2, 90, 45));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btComercialShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComercialShoppingActionPerformed
       CM2 PurchaseWindow = new CM2();
        this.dispose();
        PurchaseWindow.setVisible(true);
    }//GEN-LAST:event_btComercialShoppingActionPerformed

    private void btComercialSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComercialSaleActionPerformed
        CM1 SaleWindow = new CM1();
        this.dispose();
        SaleWindow.setVisible(true);
    }//GEN-LAST:event_btComercialSaleActionPerformed

    private void lbZooLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbZooLogoMouseClicked
        X1 MainScreen = new X1();
        this.dispose();
        MainScreen.setVisible(true);
    }//GEN-LAST:event_lbZooLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        }catch (Exception e){
            
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IS2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label LbComercialTitle;
    private javax.swing.JPanel bg;
    private Clases.PanelRound bgPanelRound;
    private javax.swing.JButton btComercialSale;
    private javax.swing.JButton btComercialShopping;
    private javax.swing.JLabel lbTicket;
    private javax.swing.JLabel lbZooLogo;
    // End of variables declaration//GEN-END:variables
}
